### ISSUE TITLE
Broken link for data files

### ISSUE THREAD

**Issue by tongue303** [griffinfoster/fundamentals_of_interferometry#109]
I have been learning a lot from this textbook.
The link to the data is broken and it would be great if you could re-post the data in dropbox.

**Comment by tongue303** [comment]
I found the live link as following.

http://math_research.uct.ac.za/~siphelo/admin/interferometry/data/fundamentals_fits.tar.gz
http://math_research.uct.ac.za/~siphelo/admin/interferometry/data/simulated_KAT-7_ms.tar.gz

Thanks

**Comment by o-smirnov** [comment]
Thanks for chasing that up! I've made a Dropbox folder and changed the URL in the README accordingly.
