### ISSUE TITLE
Interact widget in section 4.0 doesn't work for me

### ISSUE THREAD

**Issue by o-smirnov** [griffinfoster/fundamentals_of_interferometry#33]
Had to add ipywidgets to requirements.txt to get the code to compile in the first place... but  then I don't see any widget. @JulienNGirard ?

**Comment by JulienNGirard** [comment]
Yes, that's what we discussed with Griffin.
Widgets are being implemented. For the moment, only the 4_0 (compute the equivalent radio baseline) and antenna selection 4_4 (uv tracks) are widgets.
I wanted to have a complete version of the section first before investing time into improving the interactivity. As the default plots exists, this is more a matter of optimizing the length, therefore, this will be done in the review period.

**Comment by o-smirnov** [comment]
Hmmm, but the issue is, I don't even see the widget on my screen. So there's some kind of installation requirement to make it all work. Any idea?

**Comment by o-smirnov** [comment]
Hmmm sorry I think my virtualenv was not set up correctly.

**Comment by JulienNGirard** [comment]
you need either to add   ipywidgets==4.1.1 to your requirements.txt
or simply
pip install ipywidgets

should work.
