### ISSUE TITLE
requirements.txt is super-restrictive

### ISSUE THREAD

**Issue by o-smirnov** [griffinfoster/fundamentals_of_interferometry#51]
The current version doesn't even work, as it specifies some extremely specific package version numbers that pip is unable to find. Must we have such specific version numbers?

**Comment by griffinfoster** [comment]
The requirements.txt file is created by using pip freeze (https://pip.pypa.io/en/stable/reference/pip_freeze/) which is not ideal, as it doesn't take care of package ordering. I recommend just running the manual pip install commands for now. @bennahugo had the idea to write a makefile which would in part take care of the requirements.txt issues.

**Comment by o-smirnov** [comment]
Hmmm, wouldn't a requirements.txt consisting of

```
yolk
numpy
matplotlib
scipy
ipython[all]
astropy
aplpy
ipywidgets
```

...be the equivalent of the manual commands?

**Comment by griffinfoster** [comment]
ha, that is a fine idea

**Comment by griffinfoster** [comment]
this has been fixed
