### ISSUE TITLE
Corrupted svg files?

### ISSUE THREAD

**Issue by timstaley** [griffinfoster/fundamentals_of_interferometry#81]
Just a heads up that two image svgs for the introductory appendix seem to be corrupted:
https://github.com/griffinfoster/fundamentals_of_interferometry/blob/master/0_Introduction/figures/conversion-comp.svg
https://github.com/griffinfoster/fundamentals_of_interferometry/blob/master/0_Introduction/figures/conversion2-comp.svg

p.s. Thanks for putting this together, looks to be a brilliant resource!

**Comment by griffinfoster** [comment]
@JulienNGirard could you fix these figures?

**Comment by JulienNGirard** [comment]
Yep, fixing them right now.

**Comment by JulienNGirard** [comment]
Ok, something is messed up with my version of the course. Somebody has edited it and I may have a lot of conflict. I corrected the svg and sending them to you (Griffin) by email.
Cheers
