### ISSUE TITLE
Some SVG files may not work in Mozilla Firefox

### ISSUE THREAD

**Issue by jfunction** [griffinfoster/fundamentals_of_interferometry#94]
I noticed Firefox not displaying an SVG file, and on further investigation realised why. 

Firefox is very strict and needs to be told where to find the Inkscape/Sodipodi schema. Most SVG software knows about the common SVG editors and their schema so it's not a problem, but to be sure you should ensure that the following attributes are in the <svg> tag inside figures:
```<svg xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape">```

Otherwise you may get an error like "XML Parsing Error: prefix not bound to a namespace" when you try open the figure in your browser. 

I ran a hacky script to check for the error and it looks like there's only one offender on my end. 

```[bash]
find | grep .svg | xargs -0 python -c "from __future__ import print_function;import sys; [print(f) if ('inkscape:' in t and not 'xmlns:inkscape' in t) or ('sodipodi:' in t and not 'xmlns:sodipodi' in t) else None for (f,t) in ((f,open(f).read()) for f in sys.argv[1].split())]"
```

I have a fork of Bens fork which is itself a fork of the project. And my fork has uncommitted/breaking/old changes. What a mess. So would someone else be so kind as to fix this? The only file that does this is [fundamentals_of_interferometry/0_Introduction/figures/conversion-comp.svg](https://github.com/griffinfoster/fundamentals_of_interferometry/blob/master/0_Introduction/figures/conversion-comp.svg)

**Comment by griffinfoster** [comment]
Thanks for the find, I have regenerated the SVG, seems to be fine now. It seems that old versions of Inkscape didn't generate complete metadata. If we see this problem again the easy fix is to re-save the file in a newer version.
